# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX.xci
# IP: The module: 'DAPHNE_TX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAPHNE_TX'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAPHNE_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX.xci
# IP: The module: 'DAPHNE_TX' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAPHNE_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DAPHNE_TX'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
