set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX/DAPHNE_TX_in_context.xdc rfile:../../../loopback_v2.srcs/sources_1/ip/DAPHNE_TX/DAPHNE_TX/DAPHNE_TX_in_context.xdc id:1 order:EARLY scoped_inst:TX/DAPHNE_TX_support_i} [current_design]
set_property SRC_FILE_INFO {cfile:/home/daphnelme/Desktop/DAPHNE_TEST/2nd/loopback_v2/loopback_v2.srcs/constrs_1/new/const.xdc rfile:../../../loopback_v2.srcs/constrs_1/new/const.xdc id:2} [current_design]
current_instance TX/DAPHNE_TX_support_i
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 8.334 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 4.167 [get_ports {}]
current_instance
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F11 [get_ports  GTP_CLK_P]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E11 [get_ports  GTP_CLK_N]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B7  [get_ports  txp ]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A7  [get_ports  txn ]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AA4 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  AB4 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN  J8 [get_ports reset]
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN G6 [get_ports sfp_dis0]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN K8 [get_ports sfp_dis1]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN C4 [get_ports led0]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN B5 [get_ports led1]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN A5 [get_ports led2]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN B4 [get_ports led3]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN A4 [get_ports led4]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property  PACKAGE_PIN D3 [get_ports led5]
set_property src_info {type:XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells DAPHNE_TX_support_i/inst/DAPHNE_TX_init_i/DAPHNE_TX_i/gt0_DAPHNE_TX_i/gtpe2_i]
